sudo: required
services:
  - docker

before_install:
  -docker build -t thevivekpandey/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thevivekpandey/react-test npm test -- --coverage

after_success:
  - docker build -t thevivekpandey/multi-client ./client
  - docker build -t thevivekpandey/multi-nginx ./nginx
  - docker build -t thevivekpandey/multi-server ./server
  - docker build -t thevivekpandey/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push thevivekpandey/multi-client
  - docker push thevivekpandey/multi-nginx 
  - docker push thevivekpandey/multi-server
  - docker push thevivekpandey/multi-worker
